### ISSUE TITLE
This CSS url() shouldn't point to imgur

### ISSUE THREAD

**Issue by BrynM** [jejechan/jejechan#6]
Just a friendly note that this CSS file shouldn't be using us as a source for the url(). It violates the "don't use us as a CDN" potion of our TOS. You might want to change it. ;)

https://github.com/jejechan/jejechan/blob/fab82d96b9c311d5147cae855188208417922ff2/stylesheets/8ch.cyber.css#L196

**Comment by rmrhz** [comment]
Yo @BrynM, I think you should contact also @barrucadu as we was the original author of the stylesheet. Already noted and removed from this repo.

**Comment by BrynM** [comment]
Thank you! I'll follow-up with them.
